audio:
  sample_rate: 44100
model:
  dim_f: 2048
  dim_t: 256
  n_fft: 4096
  hop_length: 1024
  primary_stem: acoustic_guitar
training:
  instruments:
    - acoustic_guitar
    - other
  target_instrument: acoustic_guitar
inference:
  batch_size: 1
  overlap: 0.5
  denoise: false
